// =====================================================================
//  Mock parts catalog -- maps a scanned QR label to a Part record.
//
//  Backed by /sdcard/parts.json (see sd-assets/parts.json in the repo,
//  generated by scripts/gen_mock_qr.py). QR payloads look like
//  "MOCK-PART-00001"; the firmware resolves them to a part via lookup().
//
//  This is the prototype stand-in for a real Inventree part lookup.
//  If the SD card or parts.json is missing, the catalog is simply
//  empty and lookups fail (the Load screen falls back to "Simulate
//  scan" + reports unrecognised codes).
// =====================================================================
#pragma once

#include "ui/app_state.h"

namespace parts_catalog {

// Read /sdcard/parts.json into the in-RAM table. Safe to re-call
// (replaces the table). Returns true if at least one part loaded.
bool load();

// Number of parts currently in the table.
int count();

// Resolve a scanned QR label to a Part. Returns true and fills `out`
// on an exact match; returns false (and leaves `out` untouched) if the
// label is unknown.
bool lookup(const char* qr, app::Part& out);

// QR label of the i-th entry (0..count()-1), or nullptr if out of
// range. Used by the Load screen's "Simulate scan" to pick a code.
const char* qr_at(int i);

} // namespace parts_catalog
